# docker-compose.yaml
version: "3"

services:
  server-app:
        # Этим ключом мы скажем docker-compose, чтобы он собирал Dockerfile, который
        # находится в папке рядом с docker-compose.yaml
    build:
          context: .
          dockerfile: Dockerfile.server
        # Проброс порта так же, как в командной строке — на какой порт хоста какой порт контейнера
    ports:
      - "4000:3000"
        # Проброс файлов, откуда с хоста, куда в контейнер
    
  server-admin:
        # Этим ключом мы скажем docker-compose, чтобы он собирал Dockerfile, который
        # находится в папке рядом с docker-compose.yaml
    build:
          context: .
          dockerfile: Dockerfile.admin
        # Проброс порта так же, как в командной строке — на какой порт хоста какой порт контейнера
    ports:
      - "3100:8080"
        # Проброс файлов, откуда с хоста, куда в контейнер
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    # volumes:
    # - data-volume:/data/db